export  const AuthSuccess = 'Successful authentication';
export const AuthError = 'Unsuccessful Authentication'
export  const FoundSearch = 'Successful FoundSearch';
export const SearchNotFount = 'Unsuccessful Search'
export const LogOut = 'logging_user_out';
export const GetApplications = 'getting_all_user_applications'
export const FailedGetApplications ='getting_all_user_applications_failed'
export const EDITAPPLICATION = 'editing_particular_application'
export const GETPARTICULARAPPLICATION = 'fetching_particular_application'
export const DELETE_APPLICATION ="deleting_particular_application"
export const SuccessfulApplication = 'successful_application'
export const ErrorApplication='application_not_successful'
export const GetAllDoctors='get_all_doctors_profiles'
export const GetAllDoctorsError='error_in_getting_doctors_profile'
export const GetAllDoctorsLoad='error_in_getting_doctors_profile_load'
export  const LOAD = 'doctorAndPatientDetails';
export const BookingSuccess='booking_successful'
export const BookingError='booking_error'
export const PatientAppointmentsSuccess='patient_appointment_successfully_retrieved'
export const PatientAppointmentsError='patient_appointment_not_successfully_retrieved'
export const RescheduledAppointmentSuccessfully='appointment_rescheduled_successfully'
export const ErrorReschedulingAppointment='rescheduling_appointment_unsuccessful'
export const AppointmentCancellationSuccessful='appointment_cancellation_successful'
export const AppointmentCancellationError='appointment_cancellation_unsuccessful'
export const DoctorAppointmentsSuccess='doctor_appointment_successfully_retrieved'
export const DoctorAppointmentsError='doctor_appointment_not_successfully_retrieved'
export const updatePatientAppointmentStatusSuccessful='doctor_updating_patient_appointment_successful'
export const updatePatientAppointmentStatusUnsuccessful='doctor_updating_patient_appointment_unsuccessful'


// export  const AuthSuccessUserProfile = 'Successful_authentication_UserProfile';
// export  const AuthErrorUserProfile = 'UnSuccessful authentication';
